$(document).ready(function(){jQuery.validator&&(jQuery.validator.addMethod("checkUsername",function(value,element){return this.optional(element)||/^[0-9a-z]{1}[0-9a-z-_]{1,61}$/i.test(value)
},""),jQuery.validator.addMethod("checkUsernameEmail",function(value){return/^[0-9a-z-_]{3,20}$/i.test(value)||/^([\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+\.)*[\w\!\#$\%\&\'\*\+\-\/\=\?\^\`{\|\}\~]+@((((([a-z0-9]{1}[a-z0-9\-_]{0,62}[a-z0-9]{1})|[a-z])\.)+[a-z]{2,6})|(\d{1,3}\.){3}\d{1,3}(\:\d{1,5})?)$/i.test(value)
},""))}),function(window){function toggleSubmit(){var submitButton=$("button[type=submit]")
submitButton.attr("disabled",!submitButton.attr("disabled")).css("opacity",submitButton.attr("disabled")?.5:1)
}function redirectToDashboard(){window.top.location.href="/dashboard.html"}if(!app){var app={}
app.signupPage={}}app.userName=window.userName,app.login=function(username,password,form,source){source=source?source:"web"
var data={username:username,password:password}
form&&(form="#"+form),$.ajax({type:"POST",url:"/auth/login",data:data,dataType:"text",beforeSend:function(){toggleSubmit()
},error:function(e){$(form+" .loginErrorMessage").html(e.responseText),$(form+" .inputEmail").parent().addClass("has-warning"),"#desktop"==form?$(form+" .inputEmail").attr("data-content","<p class='text-center'>"+e.responseText+"</p><p class='forgot-password'>(<a href='/web/reset-password/desktop?username="+username+"'>forgot your password</a>?)</p>"):$(form+" .inputEmail").attr("data-content","<p class='text-center'>"+e.responseText+"</p><p class='forgot-password'>(<a href='/web/reset-password?username="+username+"'>forgot your password</a>?)</p>"),$(form+" .inputEmail").popover("show"),$(form+" .inputPassword").parent().addClass("has-warning")
},success:function(res){try{var user=JSON.parse(res).blob.user,firstName=user.fullname.split(" ").slice(0,-1).join(" "),lastName=user.fullname.split(" ").slice(-1).join(" "),traits={id:user.uid,username:user.username,email:user.email,createdAt:Number(user.date_add),active:"1"===user.active,alpha:user.alpha,beta:user.beta,c9version:user.c9version,firstName:firstName,lastName:lastName,name:user.fullname,no_newsletter:user.no_newsletter,subscription_on_signup:user.subscription_on_signup,premium:user.premium,region:user.region}
window.analytics.identify(String(user.uid),traits),window.analytics.track("Logged in (client-side)",{username:username,source:source})
}catch(e){window.analytics.track("Logged In but can't parse response (client-side)",{username:username,source:source})
}$("body").removeClass("logged-out"),$("body").addClass("logged-in"),"#signupForm"!=form&&setTimeout(redirectToDashboard,500)
},complete:function(){toggleSubmit()}})},app.logout=function(){$.ajax({type:"POST",url:"/auth/signout",dataType:"text",data:"x=1",success:function(){window.analytics.track("Logged out (client-side)")
var body=$("body")
body.removeClass("logged-in"),body.addClass("logged-out")}})},$("#btnLogout").bind({click:function(){return app.logout(),!1
}}),$("#btnLogin").bind({click:function(){return app.login($("#formLogin .inputEmail").val(),$("#formLogin .inputPassword").val(),"formLogin"),!1
}}),$("#formLogin").bind({keypress:function(event){return 13==event.which?(app.login($("#formLogin .inputEmail").val(),$("#formLogin .inputPassword").val(),"formLogin"),!1):void 0
}}),app.resetPassword=function(username){$.ajax({type:"POST",url:"/auth/password",data:{user:username},beforeSend:function(){toggleSubmit()
},error:function(e){$("#inpUsernameOrEmail").parent().removeClass("has-success has-feedback"),$("#inpUsernameOrEmail").parent().addClass("has-error has-feedback"),$("#inpUsernameOrEmail").parent().children("label").remove(),e.responseText.indexOf("email required")>-1&&(e.responseText="<p>Please enter a username or email address</p>"),$("#inpUsernameOrEmail").after('<label for="inpUsernameOrEmail" class="has-error"><p>'+e.responseText+"</p></label>")
},success:function(){$("#reset-password-form #login-form-content").fadeOut(800),setTimeout(function(){$("#passwordReset").fadeIn(800)
},1e3)},complete:function(){toggleSubmit()}})},app.validateResetPasswordForm=function(){return $("#resetPasswordForm").validate({debug:!0,rules:{inpUsernameOrEmail:{required:!0}},messages:{inpUsernameOrEmail:{required:"<p>Please enter a username or email address</p>",checkUsernameOrEmail:"<p>Please enter a valid username or email address (a username can only contain letters &amp; numbers)</p>"}},onsubmit:!0,onfocusout:!0,onkeyup:!1,onclick:!1,focusCleanup:!0,errorClass:"has-error",validClass:"has-success",success:function(label){label.parent().children(".glyphicon-remove").remove(),label.parent().addClass("has-success has-feedback"),label.remove()
},highlight:function(element){$(element).parent().children(".glyphicon-ok").remove(),$(element).parent().addClass("has-error has-feedback")
},unhighlight:function(element){$(element).parent().children(".glyphicon-remove").remove(),$(element).parent().removeClass("has-error has-feedback").addClass("has-success has-feedback")
}}),$("#resetPasswordForm").valid()},app.signUp=function(username,email,password,newsletter,type,source){var data={email:email,username:username,password:password,subscription_on_signup:type,no_newsletter:newsletter?1:0,source:source?source:"web",mixpanelAnonymousId:window.mixpanelAnonymousId,kissMetricsAnonymousId:window.kissMetricsAnonymousId}
return $.ajax({type:"POST",url:"/auth/create",data:data,beforeSend:function(){toggleSubmit()},error:function(e){e.responseText.indexOf("is already used")>-1?($("#inpEmail1").parent().removeClass("has-success has-feedback"),$("#inpEmail1").parent().addClass("has-error has-feedback"),$("#inpEmail1").after('<label for="inpEmail1" class="has-error"><p>'+e.responseText+"</p></label>")):e.responseText.indexOf("Name invalid")>-1?($("#inpUsername").parent().removeClass("has-success has-feedback"),$("#inpUsername").parent().addClass("has-error has-feedback"),$("#inpUsername").after('<label for="inpUsername" class="has-error"><p>'+e.responseText+"</p></label>")):e.responseText.indexOf("already exists")>-1?($("#inpUsername").parent().removeClass("has-success has-feedback"),$("#inpUsername").parent().addClass("has-error has-feedback"),$("#inpUsername").after('<label for="inpUsername" class="has-error"><p>'+e.responseText+"</p></label>")):$("#signUpFreeBtn").after('<div class="errorMessage"><p>'+e.responseText+"</p></div>")
},success:function(result){try{var user=JSON.parse(result).details,traits={id:user.uid,username:user.username,email:user.email,createdAt:Date.now(),no_newsletter:"1"===user.no_newsletter,subscription_on_signup:user.subscription_on_signup}
window.analytics.alias(String(user.uid)),window.analytics.identify(String(user.uid),traits),window.analytics.track("Signed Up (client-side)",{username:data.username,email:data.email,subscription_on_signup:data.subscription_on_signup,no_newsletter:data.no_newsletter,source:data.source})
}catch(e){window.analytics.track("Signed Up but can't parse userID returned (client-side)",{username:data.username,email:data.email,source:data.source})
}$("#sign-up-form-content").fadeOut(800),password?(app.login(username,password,"signupForm","web"),$(".activationEmailAddressSmall").html(email),"premium"==type?($(".dashboardLink").attr("href","/activate.html?start=premiumPayment"),setTimeout(function(){$("#almostDonePremium").fadeIn(800)
},1e3)):setTimeout(function(){$("#allDone").fadeIn(800)},1e3)):($(".activationEmailAddress").html(email),setTimeout(function(){$("#almostDone").fadeIn(800)
},1e3))},complete:function(){toggleSubmit()}}),!1},app.signupPage.validateSignUpFreeForm=function(){return $("#signUpForm").validate({rules:{inpUsername:{required:!0,minlength:4,maxlength:19,checkUsername:!0},inpEmail1:{required:!0,email:!0},inpEmail2:{required:!0,email:!0,equalTo:"#inpEmail1"},inpPassword:{required:!0}},messages:{inpUsername:{required:"<p>Username is required</p>",minlength:"<p>Username should be at least 4 characters long</p>",maxlength:"<p>Username can be at most 19 characters long</p>",checkUsername:"<p>Username can only contain alphanumeric characters (letters &amp; numbers)</p>"},inpEmail1:{required:"<p>Email address is required</p>",email:"<p>Valid email address is required</p>"},inpEmail2:{required:"<p>Email address is required</p>",email:"<p>Valid email address is required</p>",equalTo:"<p>Email addresses do not match</p>"},inpPassword:{required:"<p>Password is required</p>"}},onsubmit:!0,onfocusout:!0,onkeyup:!1,onclick:!1,focusCleanup:!0,errorClass:"has-error",validClass:"has-success",success:function(label){label.parent().addClass("has-success has-feedback"),label.parent().append('<span class="glyphicon glyphicon-ok form-control-feedback"></span>'),label.remove()
},highlight:function(element){$(element).parent().children(".glyphicon-ok").remove(),$(element).parent().addClass("has-error has-feedback"),$(element).parent().append('<span class="glyphicon glyphicon-remove form-control-feedback"></span>')
},unhighlight:function(element){$(element).parent().children(".glyphicon-remove").remove(),$(element).parent().removeClass("has-error")
}}),$("#signUpForm").valid()},app.resendActivation=function(email){app.resendingActivation||(app.resendingActivation=!0,$.ajax({type:"POST",url:"/auth/activationemail",data:{user:email},error:function(e){app.resendingActivation=!1,$("#inpUsernameOrEmail").parent().removeClass("has-success has-feedback"),$("#inpUsernameOrEmail").parent().addClass("has-error has-feedback"),$("#inpUsernameOrEmail").parent().children("label").remove(),e.responseText.indexOf("Name invalid")>-1?e.responseText="<p>Please enter a valid username or email address (a username can only contain letters &amp; numbers)</p>":e.responseText.indexOf("already active")>-1&&($("#inpUsernameOrEmail").parent().removeClass("has-error has-feedback"),$("#inpUsernameOrEmail").parent().addClass("has-success has-feedback"),e.responseText="<p>Your account has already been actived, so no need to resend the activation email :-)</p>"),$("#inpUsernameOrEmail").after('<label for="inpUsernameOrEmail" class="has-error"><p>'+e.responseText+"</p></label>")
},success:function(){$(".activationEmailAddress").html(email),$("#resend-activation-email-form #form-content").fadeOut(800),setTimeout(function(){$("#almostDone").fadeIn(800)
},1e3),app.resendingActivation=!1}}))},app.validateResendValidationForm=function(){return $("#resendActivationForm").validate({debug:!0,rules:{inpUsernameOrEmail:{required:!0}},messages:{inpUsernameOrEmail:{required:"<p>Please enter a username or email address</p>",checkUsernameOrEmail:"<p>Please enter a valid username or email address (a username can only contain letters &amp; numbers)</p>"}},onsubmit:!0,onfocusout:!0,onkeyup:!1,onclick:!1,focusCleanup:!0,errorClass:"has-error",validClass:"has-success",success:function(label){label.parent().children(".glyphicon-remove").remove(),label.parent().addClass("has-success has-feedback"),label.remove()
},highlight:function(element){$(element).parent().children(".glyphicon-ok").remove(),$(element).parent().addClass("has-error has-feedback")
},unhighlight:function(element){$(element).parent().children(".glyphicon-remove").remove(),$(element).parent().removeClass("has-error has-feedback").addClass("has-success has-feedback")
}}),$("#resendActivationForm").valid()},window.app=app}(window)

